matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: generic
      services: minimal
      env: DOCKER_IMAGE=ubuntu:19.04
    - os: osx
      language: minimal
script:
  - source ./travis/dist_${TRAVIS_OS_NAME}.sh
  - ./dist/weasyprint --version
