matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: generic
      services: docker
      env: DOCKER_IMAGE=ubuntu:19.04
    - os: osx
      language: generic
script:
  - source ./travis/dist_${TRAVIS_OS_NAME}.sh
  - ./dist/weasyprint --version
  - ./dist/weasyprint https://weasyprint.org/ weasyprint.pdf
  - stat weasyprint.pdf
addons:
  apt:
    packages:
    - ttf-dejavu
