matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: generic
      services: docker
    - os: osx
      language: generic
script:
  - source ./travis/dist_${TRAVIS_OS_NAME}.sh
  - source ./travis/test_${TRAVIS_OS_NAME}.sh
  - stat ./dist/weasyprint
